//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WebDataMining.rc
//
#define IDC_DEL_USER                    2
#define IDC_MODIFY                      2
#define IDC_UPDATE                      2
#define IDC_PUBLISH                     3
#define IDC_TEST                        3
#define IDC_NEW                         3
#define IDC_ADD_USER                    3
#define IDC_CLEAR_CLIPBOARD             3
#define IDC_EDIT                        4
#define IDC_PASTE_CLIPBOARD             4
#define IDC_DEL                         5
#define IDC_CLEAR_USERS                 5
#define IDC_PASTE_URL_CLIPBOARD         5
#define IDC_DELETE                      6
#define IDC_MODIFY_USER                 6
#define IDC_ADD_URL                     6
#define IDC_PUBLISH_TOPIC               7
#define IDC_SELECTED_ALL                9
#define IDC_FRESH                       10
#define IDC_EXPORT                      11
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDS_MAIN_TOOLBAR                101
#define IDP_SOCKETS_INIT_FAILED         102
#define IDD_LOGDLG                      108
#define IDD_DBLOGIN                     108
#define IDB_WRITESMALL                  110
#define IDB_WRITELARGE                  111
#define IDB_MAIN                        112
#define IDB_BUTTONS                     113
#define IDB_FILELARGE                   114
#define IDB_FILESMALL                   115
#define IDR_MAINFRAME                   128
#define IDR_WEBDATTYPE                  129
#define IDR_CONTEXT_MENU                130
#define IDR_POPMEMU                     130
#define IDR_POPUP_TOOLBAR               131
#define ID_WINDOW_MANAGER               131
#define IDR_CONTEXT_MENU1               132
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define IDB_WORKSPACE                   147
#define IDR_MENU_DIRS                   147
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define IDB_CAPTION                     150
#define IDB_TOOLBAR256                  151
#define IDB_TOOLBAR_SMALL               151
#define IDB_TOOLBARCOLD256              152
#define IDR_WINDOWS_MENU                152
#define IDB_TOOLBAR_LARGE               152
#define IDR_TREE_MENU                   153
#define IDD_INFO_DLG                    154
#define IDD_RULE_DLG                    155
#define IDD_ENTRY_DLG                   157
#define IDD_RULEGROUP_DLG               158
#define IDI_ICON1                       158
#define IDR_POPUP_MDITABS               159
#define IDD_TOPIC_DLG                   160
#define IDR_MENU_ARGS                   161
#define IDD_PICTURE_DLG                 161
#define IDD_SCHEDULE_DLG                162
#define IDD_EVERYDAY_DLG                163
#define IDD_EVERYWEEK_DLG               164
#define IDD_EVERYMONTH_DLG              165
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDD_SCHEDULE_LIST_DLG           168
#define IDI_PROPERTIES_WND_HC           168
#define IDD_TOPIC_PUBLISH_DLG           169
#define IDD_TOPIC_LIST_DLG              170
#define IDB_EXPLORER_24                 170
#define IDD_OPTIONS_GENERAL             171
#define IDD_OPTIONS_DATABASE            172
#define JPG_BACKGROUND                  172
#define IDB_SORT_24                     172
#define IDD_OPTIONS_WDMCONFIG           173
#define IDB_OPTIONSIMAGES               174
#define IDI_ICON2                       174
#define IDD_SEL_RECENT_TOPIC            175
#define IDB_FILE_VIEW                   175
#define IDD_PICTURE_LIST_DLG            176
#define IDB_FILE_VIEW_24                176
#define IDD_OPTIONS_PUBCONFIG           177
#define IDB_CLASS_VIEW                  177
#define IDD_USER_LOGIN                  178
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDD_LOGS                        180
#define IDB_MENU_IMAGES_24              180
#define IDD_USER_MANAGE                 181
#define ID_TOOLS_MACRO                  181
#define IDD_CLIPBOARD                   183
#define IDD_MODIFY_USERPASS             184
#define IDB_PROPERTIES_HC               184
#define IDD_PRIMARY_NEWS                185
#define IDD_DB_SERVER_DLG               186
#define IDD_SEL_CONTENT                 187
#define IDD_OPERATOR_UNIT               188
#define IDD_DATABASE_INFO               189
#define IDD_VIEW_DATATABLE              196
#define IDD_URL_DRAGLIST                197
#define IDD_LIST_VIEW                   198
#define IDR_THEME_MENU                  200
#define IDR_tTYPE                       201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define IDB_TREEIMGLIST                 211
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define IDI_ICON3                       218
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDI_ICON4                       219
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDI_ICON5                       220
#define IDI_ICON6                       221
#define IDI_ICON7                       222
#define IDI_ICON8                       223
#define IDI_ICON9                       224
#define IDI_ICON10                      225
#define IDI_ICON11                      226
#define IDI_ICON12                      227
#define IDI_ICON13                      228
#define IDI_ICON14                      229
#define IDI_ICON15                      230
#define IDI_ICON16                      231
#define IDI_ICON17                      232
#define IDI_ICON18                      233
#define IDI_ICON19                      234
#define IDD_EXPORT                      235
#define IDD_SERVER_TABLE                236
#define IDD_SEARCH                      237
#define IDD_COLUMNCLASS_INFO            238
#define IDD_SERVER_COLUMN               239
#define IDD_RULE                        240
#define IDD_ALTER_TOPIC                 241
#define IDD_IMPORT_SERVER_COLUMN        242
#define IDD_ALTER_PICTURE               243
#define IDI_EXTRACT_SOURCE_VIEW_HC      246
#define IDI_EXTRACT_SOURCE_VIEW         247
#define IDI_EXTRACT_RULE_VIEW_HC        248
#define IDI_EXTRACT_RULE_VIEW           249
#define IDI_SCHEDULE_VIEW_HC            250
#define IDI_DBSERVER_VIEW               251
#define IDI_SCHEDULE_VIEW               252
#define IDI_DBSERVER_VIEW_HC            253
#define IDD_FTP_SERVER                  254
#define IDB_BITMAP_BACK                 255
#define IDB_FILE_BITMAP                 256
#define IDR_RIBBON                      307
#define IDB_START                       327
#define IDB_BITMAPCONNECTED             328
#define IDB_BITMAPDISCONNECTED          337
#define IDC_PASS                        1002
#define IDC_DBSERVER                    1033
#define IDC_USER                        1034
#define IDC_DATABASE                    1035
#define IDC_TOPIC_SAVE_DAYS             1036
#define IDC_TOPIC_KEYWORD               1037
#define IDC_TOPIC_VIEW_PATH             1038
#define IDC_TOPIC_TOPKEYWORD            1039
#define IDC_COMPANY_URL                 1041
#define IDC_NAME                        1042
#define IDC_MATCH_RULE                  1043
#define IDC_RULE_NAME                   1044
#define IDC_PROCESS_TYPE                1045
#define IDC_SAVE_TYPE                   1046
#define IDC_ENTRY_NAME                  1046
#define IDC_WEB_NAME                    1047
#define IDC_RULE                        1048
#define IDC_URL                         1049
#define IDC_AUTO_PUBLISH                1050
#define IDC_TOPICMAX                    1051
#define IDC_TRYTIMES                    1052
#define IDC_SAVE_IMAGE                  1053
#define IDC_BUTTON_SCHEDULE             1054
#define IDC_LIST_RULE                   1054
#define IDC_AUTO_DOWNLOAD               1055
#define IDC_COMBO_RULE                  1056
#define IDC_BUTTON_TEST                 1057
#define IDC_HEAD_TITLE                  1058
#define IDC_CONTENT                     1059
#define IDC_SUB_TITLE                   1060
#define IDC_TITLE                       1061
#define IDC_SOURCE                      1062
#define IDC_SUBJECT                     1063
#define IDC_REL1                        1064
#define IDC_COMBO_KEYWORD               1064
#define IDC_REL2                        1065
#define IDC_MAIN_TITLE                  1065
#define IDC_TYPE2                       1066
#define IDC_EXPLAIN                     1066
#define IDC_TYPE1                       1067
#define IDC_POS1                        1067
#define IDC_AUTHOR                      1068
#define IDC_POS2                        1068
#define IDC_TIME                        1069
#define IDC_VIEW_PICTURE                1070
#define IDC_SCHEDULE_NAME               1072
#define IDC_ENABLED                     1074
#define IDC_FREQ_TYPE2                  1075
#define IDC_FREQ_TYPE3                  1076
#define IDC_EVERY_DAY                   1078
#define IDC_DAY                         1079
#define IDC_MONTH2                      1080
#define IDC_SPIN1                       1083
#define IDC_MONDAY                      1084
#define IDC_SPIN_MONTH2                 1084
#define IDC_TUESDAY                     1085
#define IDC_FRIDAY                      1086
#define IDC_SATURDAY                    1087
#define IDC_THURSDAY                    1088
#define IDC_WEDNSDAY                    1089
#define IDC_SUNDAY                      1090
#define IDC_WEEK                        1091
#define IDC_SPIN_DAY                    1091
#define IDC_EVERY                       1093
#define IDC_EVERY2                      1096
#define IDC_MONTH                       1097
#define IDC_NUM                         1098
#define IDC_COMBO_DAY                   1099
#define IDC_SUBDLG                      1100
#define IDC_FREQ_SUBDAY_TYPE            1101
#define IDC_FREQ_SUBDAY_TYPE2           1102
#define IDC_TIME_TYPE                   1104
#define IDC_ONCE_TIME                   1105
#define IDC_SPIN_MONTH                  1106
#define IDC_ACTIVE_START_TIME           1106
#define IDC_COMBO_NUM                   1107
#define IDC_ACTIVE_END_TIME             1107
#define IDC_FREQ_TYPE                   1109
#define IDC_ACTIVE_START_DATE           1110
#define IDC_ACTIVE_END_DATE             1111
#define IDC_RADIO_END                   1112
#define IDC_RADIO_END2                  1113
#define IDC_LIST_SCHEDULE               1116
#define IDC_SPIN_NUM                    1117
#define IDC_COMBO_COLUMN                1118
#define IDC_COMBO_ENTRY                 1119
#define IDC_TAB                         1120
#define IDC_LIST_TOPIC                  1121
#define IDC_OUTER                       1123
#define IDC_OUTER2                      1124
#define IDC_INNER                       1124
#define IDC_BUTTON_FILE                 1126
#define IDC_SERVER_PIC_SAVE_DIR         1127
#define IDC_BUTTON_PIC                  1128
#define IDC_ONE                         1129
#define IDC_AUTORUN                     1130
#define IDC_DOWNLOAD_FILE_SAVE_DIR      1131
#define IDC_FILE_SAVE_DIR               1131
#define IDC_AUTO_SEPERATE               1132
#define IDC_THREADMAX                   1133
#define IDC_LIST_PICTURE                1135
#define IDC_PREVIEW                     1140
#define IDC_SQL                         1143
#define IDC_LIST_TOPIC_UNIT             1144
#define IDC_COMBO_TABLES                1145
#define IDC_LIST_TABLE_UNIT             1146
#define IDC_BUTTON_ASSOC                1147
#define IDC_COMBO_TOPCOLUMN             1148
#define IDC_BUTTON_PUBLISH              1149
#define IDC_BUTTON_VIEW                 1150
#define IDC_BUTTON_MODIFY               1151
#define IDC_RECENT_TOPIC_DATE           1152
#define IDC_BUTTON_NEXT                 1152
#define IDC_BUTTON_FILESAVE             1153
#define IDC_BUTTON_PREV                 1153
#define IDC_USER_NAME                   1154
#define IDC_BUTTON_NEW_TOPIC            1154
#define IDC_USER_PASSWD                 1155
#define IDC_COMBO_PRIVS                 1156
#define IDC_IS_SAVE_PASS                1157
#define IDC_LIST_LOGS                   1158
#define IDC_IS_AUTO_SEND_TOPIC          1158
#define IDC_DEL_LOG                     1159
#define IDC_CLEAR_LOGS                  1160
#define IDC_LAST_PAGE                   1161
#define IDC_SAVEPASSWORD                1162
#define IDC_NEXT_PAGE                   1162
#define IDC_USER_DESC                   1163
#define IDC_PREV_PAGE                   1163
#define IDC_LIST_USERS                  1164
#define IDC_FIRTST_PAGAE                1164
#define IDC_FIRST_PAGE                  1164
#define IDC_ALL_PAGE                    1165
#define IDC_CLIPBOARD                   1166
#define IDC_COMBO_BIGTYPE               1167
#define IDC_COMBO_SMALLTYPE             1168
#define IDC_OLDPASS                     1169
#define IDC_NEWPASS                     1170
#define IDC_LIST                        1170
#define IDC_PICTURE_WIDTH               1172
#define IDC_PICTURE_HEIGHT              1173
#define IDC_CLOSE_TO_TRAY               1174
#define IDC_PICTURE_MAXSIZE             1174
#define IDC_MIMI_TO_TRAY                1175
#define IDC_VIEW_COLUMNID               1176
#define IDC_TOPIC_TOPTIME               1177
#define IDC_TOPIC_MODIFY_PATH           1178
#define IDC_PROMPT                      1179
#define IDC_UNIT_LEN                    1180
#define IDC_CHECK_NUM                   1188
#define IDC_CHECK_REL2                  1189
#define IDC_CHECK_REL1                  1190
#define IDC_UNIT_DEFAULT                1191
#define IDC_UNIT_NAME                   1195
#define IDC_CHECK_KEY                   1196
#define IDC_TREE                        1197
#define IDC_CHECK_PIC_ID                1198
#define IDC_CHECK_PIC_URL               1199
#define IDC_CHECK_PIC_EXPLAIN           1201
#define IDC_CHECK_PIC_POS               1202
#define IDC_PORTNUM                     1203
#define IDC_IPADDRESS_BROADCAST         1205
#define IDC_COMBO_TABLE                 1206
#define IDC_LIST_SELECTING_FIELD        1207
#define IDC_LIST_SELECTED_FIELD         1208
#define IDC_LIST_CONTENT                1209
#define IDC_ADD                         1210
#define IDC_SERVER_COLUMNID             1212
#define IDC_LIST_URL                    1213
#define IDC_SERVER_CHANNELID            1213
#define IDC_DEL_URL                     1214
#define IDC_CLEAR_URL                   1215
#define IDC_PAGENUM                     1218
#define IDC_KEYWORD_PREV                1219
#define IDC_KEYWORD_NEXT                1220
#define IDC_LIST_TOPCOLUMN              1220
#define IDC_ADVANCED                    1221
#define IDC_SELALL                      1222
#define IDC_DEFAULTBOX                  1223
#define IDC_SQLSERVER                   1224
#define IDC_CONFIG                      1224
#define IDC_ACCESS                      1225
#define IDC_REPEAR                      1225
#define IDC_REPAIR                      1225
#define IDC_DIR                         1228
#define IDC_BUTTON_BROWSE               1229
#define IDC_PUB_NEW                     1230
#define IDC_PUB_OLD                     1231
#define IDC_PIC_DIR                     1234
#define IDC_FILE_DIR                    1235
#define IDC_BROWSE                      1236
#define IDC_TABLE_TYPE                  1237
#define IDC_RADIO3                      1238
#define IDC_PICTURE_DIR                 1238
#define IDC_RADIO4                      1239
#define IDC_SEARCH_NEXT                 1240
#define IDC_TARGET                      1241
#define IDC_CHECK_ALL                   1242
#define IDC_XML                         1246
#define IDC_TXT                         1247
#define IDC_LANWAN                      1248
#define IDC_APPLY                       1250
#define IDC_CHECK_PRIMARY               1251
#define IDC_CHECK_PRIMARY2              1251
#define IDC_COLUMN_NAME                 1258
#define IDC_COLUMN_ID                   1259
#define IDC_COLUMN                      1259
#define IDC_SERVER_COLUMN               1260
#define IDC_ENCODING_TYPE               1261
#define IDC_RADIO2                      1262
#define IDC_TOPIC_UNIT                  1263
#define IDC_NEW_VALUE                   1265
#define IDC_VALUE                       1266
#define IDC_NUMBER                      1266
#define IDC_WEIGHT                      1266
#define IDC_CODE                        1267
#define IDC_PRIMARY_NUMBER              1268
#define IDC_CHECK_RPIMARY1              1272
#define IDC_COMBO_DATABASE              1278
#define IDC_LIST_FIELD_MAP              1279
#define IDC_PROGRESS_UPDATE             1280
#define IDC_ROOT_VALUE                  1281
#define IDC_PASTE_CODE                  1283
#define IDC_MAX_MISSION                 1284
#define IDC_FORMAT                      1285
#define IDC_FILTER                      1286
#define IDC_DATABASE_TYPE               1287
#define IDC_DATETIMEPICKEK              1288
#define IDC_DATETIME                    1288
#define IDC_COMBO1                      1290
#define IDC_INTERPOLATION               1290
#define IDC_COMBO_CODE                  1290
#define IDC_COMBO_DIR                   1290
#define IDC_COMBO_UNIT_NAME             1290
#define IDC_BUTTON_NEWID                1295
#define IDC_BUTTON_TIME                 1296
#define IDC_EDIT_MYSQL_DRIVE            1296
#define IDC_PORT                        1297
#define IDC_ORACEL                      1298
#define IDC_MYSQL                       1299
#define IDC_TREE_SERVER_COLUMNS         1300
#define IDC_EDIT1                       1302
#define IDC_PROCESS_ORDER               1302
#define IDC_SEPARATOR                   1302
#define IDC_FILE_SERVER_NAME            1302
#define IDC_EDIT_DIR                    1302
#define IDC_EDIT_DEFAULT                1302
#define IDC_ROOT                        1303
#define IDC_EDIT_ROOT                   1304
#define IDC_EDIT_ROOT_VALUE             1304
#define IDC_LIST_UNIT_COMBO             1306
#define IDC_BUTTON_UP                   1307
#define IDC_BUTTON_DOWN                 1308
#define IDC_CHECK_ONTOP                 1309
#define IDC_CHECK_ELITE                 1310
#define IDC_CHECK1                      1310
#define IDC_CHECK_AUTOID                1310
#define IDC_CHECK_ANONYMOUS             1310
#define IDC_CHECK_ISTHUMB               1310
#define IDC_CHECK_CACHE_VALUE           1310
#define IDC_CHECK_REPEAT                1310
#define IDC_BUTTON_DEL                  1311
#define IDC_EDIT_PROCESS_ORDER          1312
#define IDC_UNIT_TYPE                   1313
#define IDC_BUTTON_SAVE                 1314
#define IDC_FILE_SEND_TYPE              1315
#define IDC_FILE_SERVER_USER_NAME       1316
#define IDC_FILE_SERVER_PASSWORD        1317
#define IDC_FILE_SERVER_PORT            1318
#define IDC_FTP                         1320
#define IDC_LIST_SERVER_CONTENT         1321
#define IDC_BUTTON_BACK                 1322
#define IDC_CHECK_THUMB                 1324
#define IDC_EDIT_THUMBNAME              1325
#define IDC_BUTTON_ADD                  1327
#define IDC_CHECK3                      1330
#define IDC_UNIT_NULL                   1334
#define IDC_UNIT_KEY                    1335
#define IDC_RADIO1                      1336
#define IDC_CHECK_HEADTITLE             1400
#define IDC_CHECK_TITLE                 1401
#define IDC_CHECK_MAITITLE              1402
#define IDC_CHECK_SUBTITLE              1403
#define IDC_CHECK_TIME                  1404
#define IDC_CHECK_AUTHOR                1405
#define IDC_CHECK_SOURCE                1406
#define IDC_CHECK_CONTENT               1407
#define IDC_CHECK_KEYWORD               1408
#define IDC_CHECK_SUBJECT               1409
#define IDC_CHECK_BIGCLASS              1410
#define IDC_CHECK_SMALLCLASS            1411
#define IDC_CHECK_ISPRIMARY             1412
#define IDC_CHECK_ISELITE               1413
#define IDC_CHECK_ISONTOP               1414
#define IDC_CHECK_TOPICID               1415
#define IDC_CHECK_COLUMNID              1416
#define IDC_CHECK_RESOURCENUM           1417
#define IDC_CHECK_RESOURCEID            1418
#define IDC_CHECK_RESOURCENAME          1419
#define IDC_CHECK_RESOURCEURL           1420
#define IDC_CHECK_RESOURCE_EXPLAIN      1421
#define IDC_CHECK_RESOURCEEXT           1422
#define IDC_CHECK_TIMESTAMP             1423
#define IDC_CHECK_LINKURL               1424
#define IDC_CHECK_CHANNELID             1425
#define IDC_CHECK_EDITOR                1426
#define IDC_CHECK_PRIMARY_NUMBER        1427
#define IDC_CHECK_DEFAULT               1428
#define IDC_CHECK_SERVER_AUTOID         1429
#define IDC_CHECK_RESOURCE_SIZE         1430
#define IDC_CHECK_OLDTITLE              1431
#define IDC_CHECK_OLDURL                1432
#define ID_VIEW_CUSTOMIZE               32770
#define ID_VIEW_TOOLBARS                32771
#define IDC_START_DOWNLOAD              32771
#define IDC_STOP_ATONCE                 32772
#define IDC_STOP_AFTER_FILE             32773
#define IDC_STOP_AFTER_ENTRY            32775
#define IDC_VIEW_LOG                    32783
#define IDC_SEND_TO_SERVER              32788
#define IDC_TIME_DOWNLOAD               32791
#define ID_VIEW_WORKSPACE2              32792
#define ID_VIEW_EXTRACT_RULE            32792
#define ID_VIEW_USER_TOOLBAR1           32793
#define ID_VIEW_USER_TOOLBAR2           32794
#define ID_VIEW_USER_TOOLBAR3           32795
#define ID_APP_AUTO_RUN                 32795
#define ID_VIEW_USER_TOOLBAR4           32796
#define ID_VIEW_USER_TOOLBAR5           32797
#define ID_AUTOSENDTOSERVER             32797
#define ID_VIEW_USER_TOOLBAR6           32798
#define ID_VIEW_USER_TOOLBAR7           32799
#define ID_VIEW_USER_TOOLBAR8           32800
#define ID_VIEW_USER_TOOLBAR9           32801
#define ID_VIEW_USER_TOOLBAR10          32802
#define ID_VIEW_WORKSPACE               32803
#define ID_VIEW_EXTRACT_SOURCE          32803
#define ID_VIEW_OUTPUT                  32804
#define ID_TOOLS_ENTRY                  32805
#define ID_USER_TOOL1                   32806
#define ID_USER_TOOL2                   32807
#define ID_USER_TOOL3                   32808
#define ID_USER_TOOL4                   32809
#define ID_USER_TOOL5                   32810
#define ID_USER_TOOL6                   32811
#define ID_USER_TOOL7                   32812
#define ID_USER_TOOL8                   32813
#define ID_USER_TOOL9                   32814
#define ID_USER_TOOL10                  32815
#define ID_VIEW_CAPTIONBAR              32816
#define ID_VIEW_WORKSPACE3              32817
#define ID_VIEW_SHCEDULE                32817
#define ID_VIEW_SCHEDULE                32817
#define ID_VIEW_OUTPUT1                 32818
#define ID_VIEW_OUTPUT2                 32819
#define ID_VIEW_OUTPUT3                 32820
#define ID_VIEW_OUTPUT4                 32821
#define ID_VIEW_OUTPUT5                 32822
#define ID_VIEW_OUTPUT6                 32823
#define ID_VIEW_OUTPUT7                 32824
#define ID_VIEW_OUTPUT8                 32825
#define ID_VIEW_OUTPUT9                 32826
#define ID_VIEW_OUTPUT10                32827
#define ID_COMMON_SEPERATE              32828
#define ID_COLUMN_DOWNLOAD              32829
#define ID_COLUMN_SEPARATE              32830
#define ID_RULE_NEW                     32831
#define ID_RULE_DELETE                  32832
#define ID_ROOT_NEW                     32833
#define ID_RULE_EDIT                    32834
#define ID_ROOT_SAVE                    32835
#define ID_ROOT_DELETE                  32836
#define ID_COLUMN_EDIT                  32837
#define ID_COLUMN_DELETE                32838
#define ID_COLUMN_SAVE                  32839
#define ID_ENTRY_EDIT                   32840
#define ID_ENTRY_SAVE                   32841
#define ID_ENTRY_DELETE                 32842
#define ID_ENTRY_DOWNLOAD               32843
#define ID_ENTRY_SEPARATE               32844
#define ID_COLUMN_NEWENTRY              32845
#define ID_ENTRY_SELRULE                32846
#define ID_RULE_SAVE                    32847
#define ID_MENU_DIR1                    32847
#define ID_MENUITEM32848                32848
#define ID_MENU_DIR2                    32848
#define ID_MENU_DIR3                    32849
#define ID_TEST                         32850
#define ID_ROOT_FRESH                   32851
#define ID_ROOT_DOWNLOAD                32852
#define ID_ROOT_SEPARATE                32853
#define ID_TOPIC_EDIT                   32854
#define ID_TOPIC_DELETE                 32855
#define ID_TOPIC_SAVE                   32856
#define ID_TOPIC_PUBLISH                32857
#define ID_PICTURE_EDIT                 32858
#define ID_PICTURE_DELETE               32859
#define ID_PICTURE_SAVE                 32860
#define ID_FILE_CONNECT_DB              32861
#define ID_SCHEDULE_EDIT                32863
#define ID_SCHEDULE_DELETE              32864
#define ID_SCHEDULE_SAVE                32865
#define ID_MENU_ITEM1                   32866
#define ID_MENU_ITEM2                   32867
#define ID_TOOL_OPTIONS                 32867
#define ID_MENU_ITEM3                   32868
#define ID_RULE_TEST                    32869
#define ID_ROOT_DEL_TOPIC               32870
#define ID_COLUMN_DEL_TOPIC             32871
#define ID_ENTRY_DEL_TOPIC              32872
#define ID_COLUMN_NEW                   32873
#define ID_FILE_SHOW_RECENT_TOPIC       32874
#define ID_FILE_SENDTO_SERVER           32875
#define ID_FILE_DEL_OLDTOPICS           32876
#define ID_FILE_CLEAR_OLDURL            32877
#define ID_TOOL_VIEW_LOG                32878
#define ID_TOOL_USER                    32879
#define ID_TOOL_VIEW_USERS              32880
#define ID_TOOL_VIEW_LOGS               32881
#define ID_FILE_LOGIN                   32882
#define ID_FILE_DOWNLOAD_MANUAL         32885
#define ID_TOOL_PRIMARY_NEWS            32886
#define ID_COLUMN_SCHEDULE              32887
#define ID_ENTRY_SCHEDULE               32888
#define ID_DBSERVER_EDIT                32889
#define ID_DBSERVER_DEL                 32890
#define ID_DBSERVER_SAVE                32891
#define ID_COLUMN_SET_DBSERVER          32892
#define ID_COLUMN_CANCEL_DBSERVER       32893
#define ID_DBSERVER_NEW_DB              32894
#define ID_DATABASE_EDIT                32895
#define ID_DATABASE_DEL                 32896
#define ID_DATABASE_SAVE                32897
#define ID_DATABASE_NEW_TABLE           32898
#define ID_OPERATOR_EDIT                32899
#define ID_OPERATOR_DEL                 32900
#define ID_OPERATOR_SAVE                32901
#define ID_OPERATOR_NEW_UNIT            32902
#define ID_TABLE_EDIT                   32903
#define ID_TABLE_DEL                    32904
#define ID_TABLE_SAVE                   32905
#define ID_TABLE_NEW_OPERATOR           32906
#define ID_UNIT_EDIT                    32907
#define ID_UNIT_DEL                     32908
#define ID_UNIT_SAVE                    32909
#define ID_TOPIC_DEL_PICTURE            32910
#define ID_FILE_AUTO_SEND               32911
#define ID_FILE_SHOW_TOPCOLUMN          32912
#define ID_SENDTOPIC                    32914
#define ID_SENDTOPIC_SERVER             32916
#define ID_FILE_IMPORT                  32933
#define ID_FILE_EXPORT                  32934
#define ID_COLUMN_FRESH                 32935
#define ID_ENTRY_FRESH                  32936
#define ID_EXPORT                       32937
#define ID_IMPORT                       32938
#define ID_SEARCH                       32939
#define ID_TOOL_SEARCH                  32940
#define ID_COLUMN_SET_CHANNELID         32941
#define ID_ENTRY_SET_COLUMNID           32942
#define ID_COLUMN_SET_SUBJECT           32943
#define ID_COLUMN_SET_REL1              32944
#define ID_TOPIC_CUT                    32945
#define ID_TOPIC_PASTE                  32946
#define ID_PICTURE_CUT                  32947
#define ID_ENTRY_PASTE_TOPIC            32948
#define ID_TOPIC_PASTE_PIC              32949
#define ID_ALTER_TOPIC_UNIT             32950
#define ID_STOP_ALL_DOWNLOAD            32951
#define ID_ENTRY_NEW_TOPIC              32952
#define ID_TOOL_IMPORT_SERVER_COLUMN    32953
#define ID_TOOL_INIT_TOOLBAR            32954
#define ID_COLUMN_COLLAPSE              32955
#define ID_TOOL_BACKUP_SERVER_COLUMNS   32956
#define ID_TOOL_REBACKUP_SERVER_COLUMN  32957
#define ID_BUTTON2                      32980
#define ID_HELP_TOPIC                   40215
#define ID_VIEW_WORKSPACE4              57645
#define ID_VIEW_DBSERVER                57645
#define ID_INDICATOR_NETWORK_TYPE       57646
#define ID_INDICATOR_DB_STATUS          61447
#define ID_COMMON_DOWNLOAD              61448
#define ID_INDICATOR_WORK_THREAD_NUM    61449
#define ID_INDICATOR_USER_STATUS        61450
#define ID_INDICATOR_MESSAGE            61451
#define ID_INDICATOR_PICTURE_DIR        61452
#define ID_INDICATOR_FTP_STATUS         61453

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        257
#define _APS_NEXT_COMMAND_VALUE         32994
#define _APS_NEXT_CONTROL_VALUE         1337
#define _APS_NEXT_SYMED_VALUE           109
#endif
#endif
